var retJson = {
    "code": 200,
    "data": [{
        "id": 7,
        "name": "real_auth",
        "title": "真人认证",
        "icon": "http://tx.sykj8.com/public/style/api/img/task/real_auth.png",
        "reward": "10",
        "status": 0,
        "types": "",
        "data": {}
    }, {
        "id": 8,
        "name": "name_auth",
        "title": "实名认证",
        "icon": "http://tx.sykj8.com/public/style/api/img/task/name_auth.png",
        "reward": "10",
        "status": 0,
        "types": 1,
        "data": {
            "content": "通过真人认证后，才能进行实名认证哦~",
            "desc": "立即真人认证",
            "name": "real_auth",
            "types": "",
            "status": 0
        }
    }, {
        "id": 14,
        "name": "voice",
        "title": "录语音签名",
        "icon": "http://tx.sykj8.com/public/style/api/img/task/voice.png",
        "reward": "8",
        "status": 0,
        "types": 5,
        "data": {}
    }, {
        "id": 22,
        "name": "education_auth",
        "title": "学历认证",
        "icon": "http://tx.sykj8.com/public/style/api/img/task/education_auth.png",
        "reward": "10",
        "status": 0,
        "types": 2,
        "data": {
            "content": "通过真人认证后，才能进行学历认证哦~",
            "desc": "立即真人认证",
            "name": "real_auth",
            "types": "",
            "status": 0
        }
    }, {
        "id": 23,
        "name": "car_auth",
        "title": "车辆认证",
        "icon": "http://tx.sykj8.com/public/style/api/img/task/car_auth.png",
        "reward": "15",
        "status": 0,
        "types": 3,
        "data": {
            "content": "通过真人认证后，才能进行车辆认证哦~",
            "desc": "立即真人认证",
            "name": "real_auth",
            "types": "",
            "status": 0
        }
    }, {
        "id": 24,
        "name": "house_auth",
        "title": "房产认证",
        "icon": "http://tx.sykj8.com/public/style/api/img/task/house_auth.png",
        "reward": "20",
        "status": 0,
        "types": 4,
        "data": {
            "content": "通过真人认证后，才能进行房产认证哦~",
            "desc": "立即真人认证",
            "name": "real_auth",
            "types": "",
            "status": 0
        }
    }, {
        "id": 25,
        "name": "phone_auth",
        "title": "手机认证",
        "icon": "http://tx.sykj8.com/public/style/api/img/task/phone_auth.png",
        "reward": 0,
        "status": 2,
        "types": "",
        "data": {}
    }]
}