var retJson = [{
    "id": 7,
    "user_id": 0,
    "name": "暖男",
    "selected": 0
}, {
    "id": 36,
    "user_id": 0,
    "name": "霸道总裁",
    "selected": 1
}, {
    "id": 34,
    "user_id": 0,
    "name": "高频持久",
    "selected": 0
}, {
    "id": 33,
    "user_id": 0,
    "name": "豪气大方",
    "selected": 0
}, {
    "id": 28,
    "user_id": 0,
    "name": "老司机",
    "selected": 0
}, {
    "id": 27,
    "user_id": 0,
    "name": "帅哥",
    "selected": 0
}, {
    "id": 26,
    "user_id": 0,
    "name": "会照顾人",
    "selected": 0
}, {
    "id": 25,
    "user_id": 0,
    "name": "土豪男",
    "selected": 0
}, {
    "id": 24,
    "user_id": 0,
    "name": "旅游",
    "selected": 0
}, {
    "id": 17,
    "user_id": 0,
    "name": "高富帅",
    "selected": 0
}, {
    "id": 10,
    "user_id": 0,
    "name": "闷骚",
    "selected": 0
}, {
    "id": 8,
    "user_id": 0,
    "name": "小鲜肉",
    "selected": 0
}, {
    "id": 3,
    "user_id": 0,
    "name": "大叔",
    "selected": 0
}, {
    "id": 2,
    "user_id": 0,
    "name": "肌肉猛男",
    "selected": 0
}, {
    "id": 1,
    "user_id": 0,
    "name": "成功绅士",
    "selected": 0
}]