var imgJson = {
    "result": [{
        "id": 1293,
        "is_auth": 0,
        "burn": 0,
        "time": "2021-05-27 09:18:08",
        "user_id": 3287,
        "pic": ["../../image/test/03.jpg"],
        "type": 1,
        "is_avatar": 0,
        "cover": "",
        "picthumb": ["../../image/test/03.jpg"],
        "types": 1,
        "packet": "0.00",
        "zan": 0,
        "see": 0
    }, {
        "id": 1294,
        "is_auth": 0,
        "burn": 0,
        "time": "2021-05-27 11:25:19",
        "user_id": 3287,
        "pic": ["../../image/test/1.png"],
        "type": 1,
        "is_avatar": 0,
        "cover": "",
        "picthumb": ["../../image/test/1.png"],
        "types": 1,
        "packet": "0.00",
        "zan": 0,
        "see": 0
    }, {
        "id": 1295,
        "is_auth": 0,
        "burn": 1,
        "time": "2021-05-27 11:26:24",
        "user_id": 3287,
        "pic": ["../../image/test/yaoqing.png"],
        "type": 1,
        "is_avatar": 0,
        "cover": "",
        "picthumb": ["../../image/test/yaoqing.png"],
        "types": 1,
        "packet": "0.00",
        "zan": 0,
        "see": 0
    }, {
        "id": 1296,
        "is_auth": 0,
        "burn": 0,
        "time": "2021-05-27 11:26:42",
        "user_id": 3287,
        "pic": ["../../image/test/03.jpg"],
        "type": 1,
        "is_avatar": 0,
        "cover": "",
        "picthumb": ["../../image/test/03.jpg"],
        "types": 1,
        "packet": "1.00",
        "zan": 0,
        "see": 0
    }, {
        "id": 1297,
        "is_auth": 0,
        "burn": 1,
        "time": "2021-05-27 11:29:00",
        "user_id": 3287,
        "pic": ["../../image/test/1.png"],
        "type": 1,
        "is_avatar": 0,
        "cover": "",
        "picthumb": ["../../image/test/1.png"],
        "types": 1,
        "packet": "2.00",
        "zan": 0,
        "see": 0
    }],
    "code": 200
}
var userJson = {
    "code": 200,
    "result": {
        "id": 14,
        "name": "浪人",
        "head_100": "/disk/20200907/4aaebfda738b18f11ac44d5883693dbc.jpg",
        "head_300": "/disk/20200907/4aaebfda738b18f11ac44d5883693dbc.jpg",
        "head_portrait": "/disk/20200907/4aaebfda738b18f11ac44d5883693dbc.jpg",
        "sex": "男",
        "phone": "18846520165",
        "age": "24",
        "city": "广州番禺",
        "offten_city": "广州番禺",
        "occupation": "互联网",
        "self_slogan": "互联网互联网互联网互联网互联网互联网互联网互联网互联网互联网互联网互联网互联网互联网互网互联网互联网互联网互联网互联网互联网互联网互联网互联网互联网互联网互网互联网互联网互联网互联网互联网互联网互联网互联网互联网互联网互联网互网互联网互联网互联网互联网互联网互联网互联网互联网互联网互联网互联网互联网",
        "constellation": "",
        "img_auth": 0,
        "is_online": 1,
        "is_identity_authentication": 0,
        "hide_online_time": 0,
        "nvshen": 0,
        "last_login_datetime": "在线",
        "vip_end_datetime": "0",
        "hide_distance": 0,
        "kejian": 0,
        "role": 0,
        "photo_price": null,
        "stature": "173",
        "weight": "64",
        "wxcount": null,
        "qq": null,
        "lianmai_limit": 0,
        "paypwd": "0",
        "shoushi": "",
        "hide_search": 0,
        "volley": 0,
        "zhifucount": null,
        "zhifuname": null,
        "proxy": 0,
        "invite_count": 0,
        "vip_num": null,
        "vip_count": null,
        "shouyi": "0.00",
        "dy_program": ["看电影", "交友"],
        "dy_conditions": ["看脸", "大方"],
        "send_code": "CUZXY",
        "score": "0.00",
        "tycoon": 0,
        "charm_value": 0,
        "zan": 0,
        "angel": 0,
        "video": null,
        "cover": null,
        "voice": "",
        "voice_auth": 0,
        "voice_zan": 0,
        "noble_grade": 0,
        "noble_time": 0,
        "attention": 0,
        "following": 0,
        "friend": 0,
        "birthday": "0",
        "monthly_salary": "",
        "education_background": "",
        "emotion": "",
        "realname_auth": 0,
        "register_datetime": "2020-09-07 16:40:53",
        "line_price": "0.00",
        "heart": 0,
        "zhaohu_time": 0,
        "school_of_graduation": "",
        "live_status": "",
        "is_house_purchase": "",
        "is_car_purchase": "",
        "tags": [],
        "distance": "0.0m",
        "zhaohu": 0,
        "is_vip": 0,
        "register_date": "2020年09月07日",
        "register_days": 421,
        "photo_show": [],
        "state": 0,
        "burn": 0,
        "configPersonal": null,
        "tycoonGrade": 0,
        "tycoonIcon": "/public/style/api/img/tycoon/grade_money0_big.png",
        "charmGrade": 1,
        "charmIcon": "/public/style/api/img/charm/grade_charm_big_1.png",
        "gift": [],
        "angel_min": 20,
        "defends_count": 0,
        "defends": [{
            id: 1,
            
        }],
        "task": {
            "avatar": {
                "title": "上传头像",
                "reward": "3"
            },
            "voice": {
                "title": "录语音签名",
                "reward": "8"
            },
            "info": {
                "title": "完善基本资料",
                "reward": "4"
            },
            "more_info": {
                "title": "完善更多资料",
                "reward": "3"
            },
            "perfect_info": {
                "title": "完善自我介绍",
                "reward": "10"
            }
        },
        "is_noble": 0,
        "had_voice_zan": 0,

    }
}